-- db/seed.sql
\c nba

INSERT INTO users (username, password_hash, email, created_at, updated_at, total_score)
VALUES 
('demo', '$2b$10$.z68x3792U9LyBwmghfsKexstMO7i0SeNCoDmeJa7bEFPQBnZU3bK', 'demo@example.com', NOW(), NOW(), 0),
('demo2', '$2b$10$.z68x3792U9LyBwmghfsKexstMO7i0SeNCoDmeJa7bEFPQBnZU3bK', 'demo2@example.com', NOW(), NOW(), 100),
('demo3', '$2b$10$.z68x3792U9LyBwmghfsKexstMO7i0SeNCoDmeJa7bEFPQBnZU3bK', 'demo3@example.com', NOW(), NOW(), 200);


INSERT INTO players (first_name, last_name, age, position, height_feet, height_inches, current_team, conference, division, jersey_number) VALUES
('Jabari', 'Smith Jr.', 19, 'F', 6, 10, 'Houston Rockets', 'Western', 'Southwest', 10),
('Miles', 'McBride', 21, 'G', 6, 2, 'New York Knicks', 'Eastern', 'Atlantic', 2),
('Cam', 'Reddish', 22, 'F', 6, 8, 'Los Angeles Lakers', 'Western', 'Pacific', 5),
('Coby', 'White', 22, 'G', 6, 4, 'Chicago Bulls', 'Eastern', 'Central', 0),
('Max', 'Strus', 26, 'G', 6, 5, 'Cleveland Cavaliers', 'Eastern', 'Central', 1),
('Darius', 'Garland', 22, 'G', 6, 1, 'Cleveland Cavaliers', 'Eastern', 'Central', 10),
('Evan', 'Mobley', 20, 'C', 7, 0, 'Cleveland Cavaliers', 'Eastern', 'Central', 4),
('Franz', 'Wagner', 20, 'F', 6, 9, 'Orlando Magic', 'Eastern', 'Southeast', 22),
('Jalen', 'Suggs', 20, 'G', 6, 4, 'Orlando Magic', 'Eastern', 'Southeast', 4),
('Cole', 'Anthony', 21, 'G', 6, 2, 'Orlando Magic', 'Eastern', 'Southeast', 50),
('JT', 'Thor', 19, 'F', 6, 10, 'Charlotte Hornets', 'Eastern', 'Southeast', 33),
('Svi', 'Mykhailiuk', 24, 'G', 6, 7, 'Boston Celtics', 'Eastern', 'Atlantic', 50),
('Chet', 'Holmgren', 19, 'C', 7, 0, 'Oklahoma City Thunder', 'Western', 'Northwest', 7),
('Luguentz', 'Dort', 22, 'G', 6, 4, 'Oklahoma City Thunder', 'Western', 'Northwest', 5),
('Jalen', 'Williams', 20, 'G', 6, 3, 'Oklahoma City Thunder', 'Western', 'Northwest', 8),
  ('Steven', 'Adams', '30', 'C', 7, 0, 'Memphis Grizzlies', 'Western', 'SW', '4'),
  ('Bam', 'Adebayo', '26', 'C-F', 6, 10, 'Miami Heat', 'Eastern', 'SE', '13'),
  ('Grayson', 'Allen', '28', 'G', 6, 5, 'Phoenix Suns', 'Western', 'Pac', '8'),
  ('Jarrett', 'Allen', '25', 'C', 6, 11, 'Cleveland Cavaliers', 'Eastern', 'Cen', '31'),
  ('Kyle', 'Anderson', '30', 'F', 6, 9, 'Minnesota Timberwolves', 'Western', 'NW', '1'),
  ('Giannis', 'Antetokounmpo', '29', 'F', 6, 11, 'Milwaukee Bucks', 'Eastern', 'Cen', '34'),
  ('OG', 'Anunoby', '26', 'F', 6, 8, 'New York Knicks', 'Eastern', 'Atl', '8'),
  ('Ryan', 'Arcidiacono', '29', 'G', 6, 3, 'New York Knicks', 'Eastern', 'Atl', '51'),
  ('Deni', 'Avdija', '21', 'F', 6, 9, 'Washington Wizards', 'Eastern', 'SE', '9'),
  ('Deandre', 'Ayton', '25', 'C', 7, 1, 'Portland Trail Blazers', 'Western', 'NW', '2'),
  ('LaMelo', 'Ball', '20', 'G', 6, 6, 'Charlotte Hornets', 'Eastern', 'SE', '1'),
  ('Lonzo', 'Ball', '26', 'G', 6, 6, 'Chicago Bulls', 'Eastern', 'Cen', '2'),
  ('Mo', 'Bamba', '25', 'C', 7, 0, 'Philadelphia 76ers', 'Eastern', 'Atl', '7'),
  ('Desmond', 'Bane', '24', 'G', 6, 5, 'Memphis Grizzlies', 'Western', 'SW', '22'),
  ('Harrison', 'Barnes', '31', 'F', 6, 8, 'Sacramento Kings', 'Western', 'Pac', '40'),
  ('Scottie', 'Barnes', '21', 'F', 6, 9, 'Toronto Raptors', 'Eastern', 'Atl', '4'),
  ('RJ', 'Barrett', '22', 'G-F', 6, 6, 'Toronto Raptors', 'Eastern', 'Atl', '9'),
  ('Keita', 'Bates-Diop', '27', 'F', 6, 9, 'Phoenix Suns', 'Western', 'Pac', '21'),
  ('Nicolas', 'Batum', '35', 'F-G', 6, 8, 'Philadelphia 76ers', 'Eastern', 'Atl', '40'),
  ('Bradley', 'Beal', '30', 'G', 6, 5, 'Phoenix Suns', 'Western', 'Pac', '3'),
  ('Malik', 'Beasley', '27', 'G', 6, 5, 'Milwaukee Bucks', 'Eastern', 'Cen', '5'),
  ('Davis', 'Bertans', '31', 'F', 6, 10, 'Oklahoma City Thunder', 'Western', 'NW', '9'),
  ('Patrick', 'Beverley', '35', 'G', 6, 1, 'Milwaulkee Bucks', 'Eastern', 'Atl', '21'),
  ('Bismack', 'Biyombo', '31', 'C', 6, 9, 'Oklahoma City Thunder', 'Western', 'NW', '18'),
  ('Bogdan', 'Bogdanovic', '31', 'G', 6, 6, 'Atlanta Hawks', 'Eastern', 'SE', '13'),
  ('Bojan', 'Bogdanovic', '34', 'F', 6, 8, 'New York Knicks', 'Eastern', 'Atl', '44'),
  ('Devin', 'Booker', '27', 'G', 6, 6, 'Phoenix Suns', 'Western', 'Pac', '1'),
  ('Chris', 'Boucher', '31', 'F', 6, 10, 'Toronto Raptors', 'Eastern', 'Atl', '25'),
  ('Mikal', 'Bridges', '27', 'F', 6, 7, 'Brooklyn Nets', 'Eastern', 'Atl', '1'),
  ('Miles', 'Bridges', '25', 'F', 6, 7, 'Charlotte Hornets', 'Eastern', 'SE', '0'),
  ('Malcolm', 'Brogdon', '31', 'G', 6, 5, 'Portland Trail Blazers', 'Western', 'NW', '11'),
  ('Dillon', 'Brooks', '27', 'G-F', 6, 6, 'Houston Rockets', 'Western', 'SW', '9'),
  ('Bruce', 'Brown', '27', 'G', 6, 5, 'Indiana Pacers', 'Eastern', 'Cen', '11'),
  ('Jaylen', 'Brown', '27', 'G', 6, 7, 'Boston Celtics', 'Eastern', 'Atl', '7'),
  ('Jalen', 'Brunson', '27', 'G', 6, 3, 'New York Knicks', 'Eastern', 'Atl', '11'),
  ('Thomas', 'Bryant', '26', 'C', 6, 11, 'Miami Heat', 'Eastern', 'SE', '31'),
  ('Alec', 'Burks', '32', 'G', 6, 6, 'New York Knicks', 'Eastern', 'Atl', '18'),
  ('Jimmy', 'Butler', '34', 'G-F', 6, 8, 'Miami Heat', 'Eastern', 'SE', '22'),
  ('Kentavious', 'Caldwell-Pope', '30', 'G', 6, 5, 'Denver Nuggets', 'Western', 'NW', '5'),
  ('Clint', 'Capela', '29', 'C', 6, 10, 'Atlanta Hawks', 'Eastern', 'SE', '15'),
  ('Jevon', 'Carter', '28', 'G', 6, 2, 'Chicago Bulls', 'Eastern', 'Cen', '5'),
  ('Alex', 'Caruso', '29', 'G', 6, 5, 'Chicago Bulls', 'Eastern', 'Cen', '6'),
  ('Jordan', 'Clarkson', '31', 'G', 6, 5, 'Utah Jazz', 'Western', 'NW', '00'),
  ('Nicolas', 'Claxton', '24', 'C-F', 6, 11, 'Brooklyn Nets', 'Eastern', 'Atl', '33'),
  ('John', 'Collins', '26', 'F-C', 6, 10, 'Utah Jazz', 'Western', 'NW', '20'),
  ('Zach', 'Collins', '26', 'F-C', 7, 0, 'San Antonio Spurs', 'Western', 'SW', '23'),
  ('Mike', 'Conley', '36', 'G', 6, 1, 'Minnesota Timberwolves', 'Western', 'NW', '10'),
  ('Pat', 'Connaughton', '31', 'G', 6, 4, 'Milwaukee Bucks', 'Eastern', 'Cen', '24'),
  ('Robert', 'Covington', '33', 'F', 6, 9, 'Philadelphia 76ers', 'Eastern', 'Atl', '33'),
  ('Torrey', 'Craig', '33', 'F', 6, 7, 'Chicago Bulls', 'Eastern', 'Cen', '13'),
  ('Jae', 'Crowder', '33', 'F', 6, 6, 'Milwaukee Bucks', 'Eastern', 'Cen', '99'),
  ('Cade', 'Cunningham', '20', 'G', 6, 8, 'Detroit Pistons', 'Eastern', 'Cen', '2'),
  ('Seth', 'Curry', '33', 'G', 6, 2, 'Dallas Mavericks', 'Western', 'SW', '30'),
  ('Stephen', 'Curry', '35', 'G', 6, 3, 'Golden State Warriors', 'Western', 'Pac', '30'),
  ('Anthony', 'Davis', 30, 'F-C', 6, 10, 'Los Angeles Lakers', 'Western', 'Pac', '3'),
  ('DeMar', 'DeRozan', 34, 'G', 6, 7, 'Chicago Bulls', 'Eastern', 'Cen', '11'),
  ('Donte', 'DiVincenzo', 26, 'G', 6, 4, 'New York Knicks', 'Eastern', 'Atl', '0'),
  ('Spencer', 'Dinwiddie', 30, 'G', 6, 6, 'Brooklyn Nets', 'Eastern', 'Atl', '26'),
  ('Luka', 'Doncic', 24, 'F-G', 6, 7, 'Dallas Mavericks', 'Western', 'SW', '77'),
  ('Andre', 'Drummond', 30, 'C', 6, 11, 'Chicago Bulls', 'Eastern', 'Cen', '3'),
  ('Kris', 'Dunn', 29, 'G', 6, 4, 'Utah Jazz', 'Western', 'NW', '11'),
  ('Kevin', 'Durant', 35, 'F', 6, 9, 'Phoenix Suns', 'Western', 'Pac', '35'),
  ('Joel', 'Embiid', 29, 'F-C', 7, 0, 'Philadelphia 76ers', 'Eastern', 'Atl', '21'),
  ('Drew', 'Eubanks', 26, 'F', 6, 10, 'Phoenix Suns', 'Western', 'Pac', '14'),
  ('Dante', 'Exum', 28, 'G', 6, 6, 'Dallas Mavericks', 'Western', 'SW', '0'),
  ('Dorian', 'Finney-Smith', 30, 'F', 6, 8, 'Brooklyn Nets', 'Eastern', 'Atl', '28'),
  ('Evan', 'Fournier', 31, 'G-F', 6, 7, 'New York Knicks', 'Eastern', 'Atl', '13'),
  ('De''Aaron', 'Fox', 26, 'G', 6, 3, 'Sacramento Kings', 'Western', 'Pac', '5'),
  ('Markelle', 'Fultz', 25, 'G', 6, 4, 'Orlando Magic', 'Eastern', 'SE', '20'),
  ('Danilo', 'Gallinari', '35', 'F', 6, 10, 'Washington Wizards', 'Eastern', 'SE', '88'),
  ('Paul', 'George', '33', 'F', 6, 9, 'LA Clippers', 'Western', 'Pac', '13'),
  ('Shai', 'Gilgeous-Alexander', '25', 'G', 6, 6, 'Oklahoma City Thunder', 'Western', 'NW', '2'),
  ('Rudy', 'Gobert', '31', 'C', 7, 1, 'Minnesota Timberwolves', 'Western', 'NW', '27'),
  ('Aaron', 'Gordon', '28', 'F', 6, 9, 'Denver Nuggets', 'Western', 'NW', '50'),
  ('Eric', 'Gordon', '35', 'G', 6, 4, 'Phoenix Suns', 'Western', 'Pac', '23'),
  ('Devonte''', 'Graham', '28', 'G', 6, 2, 'San Antonio Spurs', 'Western', 'SW', '4'),
  ('Jerami', 'Grant', '29', 'F', 6, 9, 'Portland Trail Blazers', 'Western', 'NW', '9'),
  ('Draymond', 'Green', '33', 'F', 6, 7, 'Golden State Warriors', 'Western', 'Pac', '23'),
  ('Jalen', 'Green', '21', 'G', 6, 4, 'Houston Rockets', 'Western', 'SW', '4'),
  ('Jeff', 'Green', '37', 'F', 6, 9, 'Houston Rockets', 'Western', 'SW', '32'),
  ('Tyrese', 'Haliburton', '23', 'G', 6, 5, 'Indiana Pacers', 'Eastern', 'Cen', '0'),
  ('James', 'Harden', '34', 'G', 6, 5, 'LA Clippers', 'Western', 'Pac', '1'),
  ('Gary', 'Harris', '29', 'G', 6, 4, 'Orlando Magic', 'Eastern', 'SE', '14'),
  ('Joe', 'Harris', '32', 'F-G', 6, 6, 'Detroit Pistons', 'Eastern', 'Cen', '31'),
  ('Tobias', 'Harris', '31', 'F', 6, 9, 'Philadelphia 76ers', 'Eastern', 'Atl', '12'),
  ('Josh', 'Hart', '28', 'G', 6, 5, 'New York Knicks', 'Eastern', 'Atl', '3'),
  ('Isaiah', 'Hartenstein', '25', 'F-C', 7, 0, 'New York Knicks', 'Eastern', 'Atl', '55'),
  ('Gordon', 'Hayward', '33', 'F', 6, 8, 'Charlotte Hornets', 'Eastern', 'SE', '20'),
  ('Tyler', 'Herro', '23', 'G', 6, 5, 'Miami Heat', 'Eastern', 'SE', '14'),
  ('Buddy', 'Hield', '31', 'G', 6, 4, 'Indiana Pacers', 'Eastern', 'Cen', '7'),
('Aaron', 'Holiday', '27', 'G', 6, 1, 'Houston Rockets', 'Western', 'SW', '0'),
('Jrue', 'Holiday', '33', 'G', 6, 4, 'Boston Celtics', 'Eastern', 'Atl', '4'),
('Justin', 'Holiday', '34', 'F-G', 6, 6, 'Denver Nuggets', 'Western', 'NW', '9'),
('Richaun', 'Holmes', '30', 'F-C', 6, 10, 'Dallas Mavericks', 'Western', 'SW', '20'),
('Al', 'Horford', '37', 'C-F', 6, 10, 'Boston Celtics', 'Eastern', 'Atl', '42'),
('Kevin', 'Huerter', '25', 'G', 6, 7, 'Sacramento Kings', 'Western', 'Pac', '9'),
('Joe', 'Ingles', '36', 'F', 6, 8, 'Orlando Magic', 'Eastern', 'SE', '7'),
('Brandon', 'Ingram', '26', 'F', 6, 9, 'New Orleans Pelicans', 'Western', 'SW', '14'),
('Kyrie', 'Irving', '31', 'G', 6, 3, 'Dallas Mavericks', 'Western', 'SW', '11'),
('Jonathan', 'Isaac', '26', 'F', 6, 10, 'Orlando Magic', 'Eastern', 'SE', '1'),
('Jaden', 'Ivey', '20', 'G', 6, 4, 'Detroit Pistons', 'Eastern', 'Cen', '4'),
('Reggie', 'Jackson', '33', 'G', 6, 3, 'Denver Nuggets', 'Western', 'NW', '7'),
('LeBron', 'James', '39', 'F', 6, 8, 'Los Angeles Lakers', 'Western', 'Pac', '23'),
('Cam', 'Johnson', '26', 'F', 6, 8, 'Brooklyn Nets', 'Eastern', 'Atl', '2'),
('Nikola', 'Jokic', '28', 'C', 7, 0, 'Denver Nuggets', 'Western', 'NW', '15'),
('Damian', 'Jones', '28', 'C', 7, 0, 'Cleveland Cavaliers', 'Eastern', 'Cen', '30'),
('Tyus', 'Jones', '27', 'G', 6, 2, 'Washington Wizards', 'Eastern', 'SE', '5'),
('DeAndre', 'Jordan', '35', 'C', 6, 11, 'Denver Nuggets', 'Western', 'NW', '6'),
('Cory', 'Joseph', '32', 'G', 6, 3, 'Golden State Warriors', 'Western', 'Pac', '1'),
('Luke', 'Kennard', '27', 'G', 6, 5, 'Memphis Grizzlies', 'Western', 'SW', '10'),
('Maxi', 'Kleber', '31', 'F', 6, 11, 'Dallas Mavericks', 'Western', 'SW', '42'),
('Kevin', 'Knox', '24', 'F', 6, 9, 'Detroit Pistons', 'Eastern', 'Cen', '24'),
('Furkan', 'Korkmaz', '26', 'G-F', 6, 7, 'Philadelphia 76ers', 'Eastern', 'Atl', '30'),
('Luke', 'Kornet', '28', 'F-C', 7, 1, 'Boston Celtics', 'Eastern', 'Atl', '40'),
('Kyle', 'Kuzma', '28', 'F', 6, 9, 'Washington Wizards', 'Eastern', 'SE', '33'),
('Zach', 'LaVine', '28', 'G', 6, 5, 'Chicago Bulls', 'Eastern', 'Cen', '8'),
('Caris', 'LeVert', '29', 'G', 6, 7, 'Cleveland Cavaliers', 'Eastern', 'Cen', '3'),
('Damion', 'Lee', '31', 'G', 6, 6, 'Phoenix Suns', 'Western', 'Pac', '10'),
('Alex', 'Len', '30', 'C', 7, 1, 'Sacramento Kings', 'Western', 'Pac', '25'),
('Kawhi', 'Leonard', '32', 'F', 6, 7, 'LA Clippers', 'Western', 'Pac', '2'),
('Damian', 'Lillard', '33', 'G', 6, 3, 'Milwaukee Bucks', 'Eastern', 'Cen', '0'),
('Kevon', 'Looney', '27', 'F', 6, 9, 'Golden State Warriors', 'Western', 'Pac', '5'),
('Brook', 'Lopez', '35', 'C', 7, 0, 'Milwaukee Bucks', 'Eastern', 'Cen', '11'),
('Robin', 'Lopez', '35', 'C', 7, 0, 'Milwaukee Bucks', 'Eastern', 'Cen', '42'),
('Kevin', 'Love', '35', 'F-C', 6, 10, 'Miami Heat', 'Eastern', 'SE', '42'),
('Kyle', 'Lowry', '37', 'G', 6, 1, 'Miami Heat', 'Eastern', 'SE', '7'),
('Trey', 'Lyles', '28', 'F', 6, 10, 'Sacramento Kings', 'Western', 'Pac', '41'),
('Boban', 'Marjanovic', '35', 'C', 7, 3, 'Houston Rockets', 'Western', 'SW', '51'),
('Lauri', 'Markkanen', '26', 'F', 7, 0, 'Utah Jazz', 'Western', 'NW', '23'),
('Wesley', 'Matthews', '37', 'G-F', 6, 5, 'Atlanta Hawks', 'Eastern', 'SE', '32'),
('Tyrese', 'Maxey', '22', 'G', 6, 2, 'Philadelphia 76ers', 'Eastern', 'Atl', '0'),
('CJ', 'McCollum', '31', 'G', 6, 3, 'New Orleans Pelicans', 'Western', 'SW', '3'),
('T.J.', 'McConnell', '31', 'G', 6, 2, 'Indiana Pacers', 'Eastern', 'Cen', '9'),
('Doug', 'McDermott', '32', 'F', 6, 8, 'San Antonio Spurs', 'Western', 'SW', '17'),
('JaVale', 'McGee', '35', 'C', 7, 0, 'Sacramento Kings', 'Western', 'Pac', '00'),
('DeAnthony', 'Melton', '25', 'G', 6, 4, 'Philadelphia 76ers', 'Eastern', 'Atl', '8'),
('Chimezie', 'Metu', '26', 'F', 6, 10, 'Phoenix Suns', 'Western', 'Pac', '4'),
('Khris', 'Middleton', '32', 'F', 6, 8, 'Milwaukee Bucks', 'Eastern', 'Cen', '22'),
('Patty', 'Mills', '35', 'G', 6, 0, 'Atlanta Hawks', 'Eastern', 'SE', '8'),
('Shake', 'Milton', '27', 'G', 6, 6, 'Minnesota Timberwolves', 'Western', 'NW', '18'),
('Donovan', 'Mitchell', '27', 'G', 6, 3, 'Cleveland Cavaliers', 'Eastern', 'Cen', '45'),
('Malik', 'Monk', '25', 'G', 6, 3, 'Sacramento Kings', 'Western', 'Pac', '0'),
('Markieff', 'Morris', '34', 'F', 6, 9, 'Dallas Mavericks', 'Western', 'SW', '88'),
('Monte', 'Morris', '28', 'G', 6, 3, 'Detroit Pistons', 'Eastern', 'Cen', '5'),
('Dejounte', 'Murray', '27', 'G', 6, 5, 'Atlanta Hawks', 'Eastern', 'SE', '5'),
('Jamal', 'Murray', '26', 'G', 6, 4, 'Denver Nuggets', 'Western', 'NW', '27'),
('Mike', 'Muscala', '32', 'F-C', 6, 11, 'Detroit Pistons', 'Eastern', 'Cen', '35'),
('Georges', 'Niang', '30', 'F', 6, 8, 'Cleveland Cavaliers', 'Eastern', 'Cen', '20'),
('Frank', 'Ntilikina', '25', 'G', 6, 6, 'Charlotte Hornets', 'Eastern', 'SE', '44'),
('Jusuf', 'Nurkic', '29', 'C', 7, 0, 'Phoenix Suns', 'Western', 'Pac', '20'),
('Royce', 'O''Neale', '30', 'F', 6, 6, 'Brooklyn Nets', 'Eastern', 'Atl', '00'),
('Josh', 'Okogie', '25', 'G', 6, 4, 'Phoenix Suns', 'Western', 'Pac', '2'),
('Victor', 'Oladipo', '31', 'G', 6, 4, 'Houston Rockets', 'Western', 'SW', '3'),
('Kelly', 'Olynyk', '32', 'F', 7, 0, 'Utah Jazz', 'Western', 'NW', '41'),
('Cedi', 'Osman', '28', 'F', 6, 8, 'San Antonio Spurs', 'Western', 'SW', '16'),
('Chris', 'Paul', '38', 'G', 6, 0, 'Golden State Warriors', 'Western', 'Pac', '3'),
('Cameron', 'Payne', '29', 'G', 6, 3, 'Phildalphia 76ers', 'Eastern', 'Atl', '22'),
('Mason', 'Plumlee', '33', 'F-C', 6, 11, 'LA Clippers', 'Western', 'Pac', '44'),
('Jakob', 'Poeltl', '28', 'C', 7, 0, 'Toronto Raptors', 'Eastern', 'Atl', '19'),
('Jordan', 'Poole', '23', 'G', 6, 4, 'Washington Wizards', 'Eastern', 'SE', '13'),
('Bobby', 'Portis', '28', 'F', 6, 11, 'Milwaukee Bucks', 'Eastern', 'Cen', '9'),
('Kristaps', 'Porzingis', '28', 'F-C', 7, 3, 'Boston Celtics', 'Eastern', 'Atl', '8'),
('Dwight', 'Powell', '32', 'F-C', 6, 11, 'Dallas Mavericks', 'Western', 'SW', '7'),
('Norman', 'Powell', '30', 'F-G', 6, 4, 'LA Clippers', 'Western', 'Pac', '24'),
('Taurean', 'Prince', '29', 'F', 6, 8, 'Los Angeles Lakers', 'Western', 'Pac', '12'),
('Immanuel', 'Quickley', '23', 'G', 6, 3, 'Toronto Raptors', 'Eastern', 'Atl', '5'),
('Julius', 'Randle', '29', 'F', 6, 9, 'New York Knicks', 'Eastern', 'Atl', '30'),
('Josh', 'Richardson', '30', 'G-F', 6, 6, 'Miami Heat', 'Eastern', 'SE', '0'),
('Duncan', 'Robinson', '29', 'F', 6, 8, 'Miami Heat', 'Eastern', 'SE', '55'),
('Jerome', 'Robinson', '26', 'G', 6, 5, 'Golden State Warriors', 'Western', 'Pac', '18'),
('Mitchell', 'Robinson', '25', 'C', 7, 1, 'New York Knicks', 'Eastern', 'Atl', '23'),
('Derrick', 'Rose', '35', 'G', 6, 3, 'Memphis Grizzlies', 'Western', 'SW', '23'),
('Terry', 'Rozier', '29', 'G', 6, 1, 'Charlotte Hornets', 'Eastern', 'SE', '3'),
('Ricky', 'Rubio', '33', 'G', 6, 4, 'Cleveland Cavaliers', 'Eastern', 'Cen', '13'),
('D''Angelo', 'Russell', '27', 'G', 6, 5, 'Los Angeles Lakers', 'Western', 'Pac', '1'),
('Domantas', 'Sabonis', '27', 'F', 6, 11, 'Sacramento Kings', 'Western', 'Pac', '10'),
('Dario', 'Saric', '29', 'F', 6, 10, 'Golden State Warriors', 'Western', 'Pac', '20'),
('Dennis', 'Schroder', '30', 'G', 6, 1, 'Toronto Raptors', 'Eastern', 'Atl', '17'),
('Collin', 'Sexton', '25', 'G', 6, 2, 'Utah Jazz', 'Western', 'NW', '2'),
('Landry', 'Shamet', '26', 'G', 6, 5, 'Washington Wizards', 'Eastern', 'SE', '20'),
('Pascal', 'Siakam', '29', 'F', 6, 9, 'Toronto Raptors', 'Eastern', 'Atl', '43'),
('Ben', 'Simmons', '27', 'G-F', 6, 10, 'Brooklyn Nets', 'Eastern', 'Atl', '10'),
('Anfernee', 'Simons', '24', 'G', 6, 4, 'Portland Trail Blazers', 'Western', 'NW', '1'),
('Marcus', 'Smart', '29', 'G', 6, 4, 'Memphis Grizzlies', 'Western', 'SW', '36'),
('Ish', 'Smith', '35', 'G', 6, 0, 'Charlotte Hornets', 'Eastern', 'SE', '14'),
('Jayson', 'Tatum', '25', 'F', 6, 8, 'Boston Celtics', 'Eastern', 'Atl', '0'),
('Garrett', 'Temple', '37', 'G-F', 6, 6, 'Toronto Raptors', 'Eastern', 'Atl', '14'),
('Daniel', 'Theis', '31', 'F', 6, 8, 'LA Clippers', 'Western', 'Pac', '10'),
('Klay', 'Thompson', '33', 'G', 6, 7, 'Golden State Warriors', 'Western', 'Pac', '11'),
('Tristan', 'Thompson', '32', 'C-F', 6, 10, 'Cleveland Cavaliers', 'Eastern', 'Cen', '13'),
('Karl-Anthony', 'Towns', '28', 'C', 7, 0, 'Minnesota Timberwolves', 'Western', 'NW', '32'),
('Myles', 'Turner', '27', 'C-F', 6, 11, 'Indiana Pacers', 'Eastern', 'Cen', '33'),
('Jonas', 'Valanciunas', '31', 'C', 7, 0, 'New Orleans Pelicans', 'Western', 'SW', '17'),
('Fred', 'VanVleet', '29', 'G', 6, 0, 'Houston Rockets', 'Western', 'SW', '5'),
('Jarred', 'Vanderbilt', '24', 'F', 6, 9, 'Los Angeles Lakers', 'Western', 'Pac', '2'),
('Nikola', 'Vucevic', '33', 'C', 7, 0, 'Chicago Bulls', 'Eastern', 'Cen', '9'),
('Moritz', 'Wagner', '26', 'C', 6, 11, 'Orlando Magic', 'Eastern', 'SE', '21'),
('Lonnie', 'Walker IV', '25', 'G', 6, 5, 'Brooklyn Nets', 'Eastern', 'Atl', '8'),
('Yuta', 'Watanabe', '29', 'G', 6, 9, 'Phoenix Suns', 'Western', 'Pac', '18'),
('Victor', 'Wembanyama', '20', 'C', 7, 4, 'San Antonio Spurs', 'Western', 'SW', '1'),
('Russell', 'Westbrook', '35', 'G', 6, 3, 'LA Clippers', 'Western', 'Pac', '0'),
('Derrick', 'White', '29', 'G', 6, 4, 'Boston Celtics', 'Eastern', 'Atl', '9'),
('Andrew', 'Wiggins', '28', 'F-G', 6, 8, 'Golden State Warriors', 'Western', 'Pac', '22'),
('Kenrich', 'Williams', '29', 'G-F', 6, 7, 'Oklahoma City Thunder', 'Western', 'NW', '34'),
('Zion', 'Williamson', '22', 'F', 6, 6, 'New Orleans Pelicans', 'Western', 'SW', '1'),
('Christian', 'Wood', '28', 'F', 6, 10, 'Los Angeles Lakers', 'Western', 'Pac', '35'),
('Delon', 'Wright', '31', 'G', 6, 5, 'Washington Wizards', 'Eastern', 'SE', '55'),
('Thaddeus', 'Young', '35', 'F', 6, 8, 'Toronto Raptors', 'Eastern', 'Atl', '21'),
('Trae', 'Young', '25', 'G', 6, 2, 'Atlanta Hawks', 'Eastern', 'SE', '11'),
('Cody', 'Zeller', '31', 'C', 7, 0, 'New Orleans Pelicans', 'Western', 'SW', '40'),
('Ivica', 'Zubac', '26', 'C', 7, 1, 'LA Clippers', 'Western', 'Pac', '40');


INSERT INTO games (correct_answer, user_id, score)
VALUES
(1, 1, 100);